# kubernetes/eks-cluster-config.yaml
# Cluster Config
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: stock-scraper-eks-cluster
  region: us-east-1
  version: "1.22"
vpc:
  subnets:
    private:
      us-east-1e: { id: subnet-0cbef60494370bfbd }
      us-east-1d: { id: subnet-06035b7cc3596e439 }
      us-east-1c: { id: subnet-01821cf8ad9afac7b }
      us-east-1b: { id: subnet-0e292fcded1f9e285 }
      us-east-1a: { id: subnet-049cf9a739eb4351b }
      us-east-1f: { id: subnet-049486fd94a204960 }
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
